plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.0-M3'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'io.freefair.lombok' version '8.6'
}

group = 'leetcode.clone'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

dependencies {
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.liquibase:liquibase-core'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation 'com.zaxxer:HikariCP:4.0.3'
	implementation 'com.github.docker-java:docker-java:3.4.0'
	implementation 'com.github.docker-java:docker-java-core:3.4.0'
	implementation 'com.github.docker-java:docker-java-transport-httpclient5:3.4.0'

	implementation group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.1'
	implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}

tasks.named('bootJar') {
	archiveBaseName = 'code-publisher'
}

tasks.named('test') {
	useJUnitPlatform()
}
